apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "backend" }}
  labels:
    {{- include "heicwallpaper.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "heicwallpaper.labels.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: "backend"
  template:
    metadata:
      labels:
        {{- include "heicwallpaper.labels.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: "backend"
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}/backend:{{ $.Values.image.tag }}{{- if $.Values.image.digest -}}@{{ $.Values.image.digest }}{{- end -}}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          envFrom:
            - secretRef:
                name: {{ $.Values.heicwallpaper.results_s3_secret_name }}
            - secretRef:
                name: {{ $.Values.heicwallpaper.upload_s3_secret_name }}
            - secretRef:
                name: {{ $.Values.heicwallpaper.authentik_secret_name }}
          env:
            - name: BROKER_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379/0"
            - name: PUBLIC_URL
              value: "{{ $.Values.heicwallpaper.public_url }}"
            - name: PUBLIC_ASSET_URL
              value: "{{ $.Values.heicwallpaper.public_asset_url }}"
            - name: DATABASE_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379/0"
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
