apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "backend" }}
  labels:
    {{- include "heicwallpaper.labels" . | nindent 4 }}
    {{- with .Values.service.backend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.backend.port }}
      protocol: {{ .Values.service.backend.protocol }}
      name: {{ .Values.service.backend.name }}
  selector:
    {{- include "heicwallpaper.labels.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "backend"
