apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "frontend" }}
  labels:
    {{- include "heicwallpaper.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "heicwallpaper.labels.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: "frontend"
  template:
    metadata:
      labels:
        {{- include "heicwallpaper.labels.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: "frontend"
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}/frontend:{{ $.Values.image.tag }}{{- if $.Values.image.digest -}}@{{ $.Values.image.digest }}{{- end -}}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
