apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "frontend" }}
  labels:
    {{- include "heicwallpaper.labels" . | nindent 4 }}
    {{- with .Values.service.frontend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.service.frontend.port }}
      protocol: {{ .Values.service.frontend.protocol }}
  selector:
    {{- include "heicwallpaper.labels.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "frontend"
