---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "worker" }}
  labels:
    {{- include "heicwallpaper.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "worker"
spec:
  replicas: {{ $.Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "heicwallpaper.labels.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      labels:
        {{- include "heicwallpaper.labels.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: "worker"
        app.kubernetes.io/version: "{{ trunc 63 $.Values.image.tag }}"
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}/worker:{{ $.Values.image.tag }}{{- if $.Values.image.digest -}}@{{ $.Values.image.digest }}{{- end -}}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          env:
            - name: BROKER_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379/0"
            - name: DATABASE_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379/0"
            - name: PUBLIC_URL
              value: "{{ $.Values.heicwallpaper.public_url }}"
          envFrom:
            - secretRef:
                name: {{ $.Values.heicwallpaper.results_s3_secret_name }}
            - secretRef:
                name: {{ $.Values.heicwallpaper.upload_s3_secret_name }}
            - secretRef:
                name: {{ $.Values.heicwallpaper.authentik_secret_name }}
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m