apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "worker" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "heicwallpaper.names.fullname" $) "worker" }}
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50