version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ./api
      target: web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./api:/app
      - ./static:/static

  redis:
    container_name: redis
    image: redis:5.0.5

  worker:
    build:
      context: ./api
      target: watchdog
    hostname: worker
    working_dir: /app
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A workers.image_processor worker --loglevel=info
    volumes:
      - ./api:/app:ro
      - ./static:/static
    links:
      - redis
    depends_on:
      - redis
