version: "3.9"

services:
    backend:
        build:
            context: .
            target: backend-prod
        ports:
            - "5000:5000"
        depends_on:
            - redis
        environment:
            - PRODUCTION=True
            - BROKER_URL=redis://redis:6379/0
        volumes:
            - ./static:/static

    redis:
        container_name: redis
        image: redislabs/rejson:2.0.9
        ports:
            - "6379:6379"

    worker:
        build:
            context: .
            target: celery
        environment:
            - BROKER_URL=redis://redis:6379/0
        volumes:
            - ./static:/static
        depends_on:
            - redis
