version: "3.9"

services:
  redis:
    container_name: redis
    image: bbilly1/rejson:v2.0.9
    ports:
      - "6379:6379"

  web:
    container_name: web
    build:
      context: ./api
      target: web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - BROKER_URL=redis://redis:6379/0
    volumes:
      - ./api:/app
      - ./static:/static
