version: '3'

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio_data:/data
  redis:
    image: redislabs/rejson:2.0.9
    ports:
      - '6379:6379'

  db:
      image: bitnami/postgresql:16
      volumes:
          - ./postgres_data:/var/lib/postgresql/data
      ports:
          - "5435:5432"
      environment:
          POSTGRESQL_USERNAME: heicwallpaper
          POSTGRESQL_DATABASE: heicwallpaper
          POSTGRESQL_PASSWORD: heicwallpaper

