version: "3.9"

services:
    frontend:
        build:
            context: .
            target: frontend
        ports:
            - "5173:5173"
        depends_on:
            - backend
        volumes:
            - ./frontend:/app

    backend:
        build:
            context: .
            target: backend
        ports:
            - "5000:5000"
        depends_on:
            - redis
        environment:
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - BROKER_URL=redis://redis:6379/0
        volumes:
            - ./backend:/backend
            - ./static:/static

    redis:
        container_name: redis
        image: redislabs/rejson:2.0.9
        ports:
            - "6379:6379"

    worker:
        build:
            context: .
            target: celery-watching
        environment:
            - BROKER_URL=redis://redis:6379/0
        volumes:
            - ./backend:/backend:ro
            - ./static:/static
        links:
            - redis
        depends_on:
            - redis
