version: "3.9"

services:
    backend:
        build:
            context: .
            target: backend-prod
        restart: always
        ports:
            - "5000"
        depends_on:
            - redis
        environment:
            - PRODUCTION=True
            - BROKER_URL=redis://redis:6379/0
        volumes:
            - ./static:/static
    nginx:
        build:
            context: .
            target: nginx-prod
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - backend
        volumes:
            - ./static:/static
        links:
            - backend

    redis:
        container_name: redis
        image: redislabs/rejson:2.0.9
        restart: always
        ports:
            - "6379:6379"

    worker:
        build:
            context: .
            target: celery
        restart: always
        environment:
            - BROKER_URL=redis://redis:6379/0
        volumes:
            - ./static:/static
        depends_on:
            - redis
