image:
  repository: ghcr.io/thiesjoo/heic-wallpaper
  tag: main
  digest: ""
  pullPolicy: Always

worker:
  replicas: 1

service:
  frontend:
    enabled: true
    type: ClusterIP
    port: 5000
    name: http
    protocol: TCP
  backend:
    enabled: true
    type: ClusterIP
    port: 5000
    name: http
    protocol: TCP

ingress:
  enabled: true
  host: wallpaper.thies.dev

heicwallpaper:
  #  Should be a pre-existing kubernetes secret with the values:
  #RESULT_S3_URL
  #RESULT_S3_BUCKET
  #RESULT_S3_ACCESS_KEY
  #RESULT_S3_SECRET_KEY
  results_s3_secret_name: "heicwallpaper-s3-result"
  upload_s3_secret_name: "heicwallpaper-s3-upload"

  #  Should be a pre-existing kubernetes secret with the values:
  #  AUTHENTIK_API_URL
  #  AUTHENTIK_CLIENT_ID
  #  AUTHENTIK_TOKEN
  authentik_secret_name: "authentik-tokens-heicwallpaper"

  public_asset_url: "https://static.wallpaper.thies.dev"
  public_url: "https://wallpaper.thies.dev"

  #  Should be a pre-existing kubernetes secret with the values:
  #  SECRET_KEY
  secret_values_secret: "heicwallpaper-general-secret"

minio:
    persistence:
        size: 1Gi
    defaultBuckets: "upload"
    auth:
      # For example:
      #    apiVersion: v1
      #    kind: Secret
      #    metadata:
      #        name: heicwallpaper-minio-creds
      #    type: Opaque
      #    stringData:
      #        root-user: admin
      #        root-password: replace_this_with_a_good_password
      existingSecret: "heicwallpaper-minio-creds"
    ingress:
      enabled: true
      hostname: "minioadmin.home.thies.dev"
    apiIngress:
      enabled: true
      hostname: upload.wallpaper.thies.dev
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: "cloudflare-thies-dev-issuer"
        nginx.ingress.kubernetes.io/proxy-body-size: "1Gi"


redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      size: 1Gi


postgresql:
    primary:
        persistence:
            storageClass: "local-path"
            size: 1Gi
    auth:
        username: "heic-wallpaper"
        database: "heicwallpaper"
        # For example:
        #    apiVersion: v1
        #    kind: Secret
        #    metadata:
        #        name: enter-existing-secret-name-postgresql
        #    type: Opaque
        #    stringData:
        #        password: replace_this_with_password
        #        postgres-password: replace_this_with_postgresPassword
        existingSecret: "heicwallpaper-postgres-creds"
