# Generated by Django 5.1.4 on 2024-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='status',
            field=models.CharField(choices=[(1, 'Ready'), (2, 'Uploading'), (3, 'Processing'), (4, 'Error')], max_length=255),
        ),
    ]
