name: CI/CD
on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        env:
            VITE_OIDC_AUTHORITY: ${{ vars.VITE_OIDC_AUTHORITY }}
            VITE_OIDC_CLIENT_ID: ${{ vars.VITE_OIDC_CLIENT_ID }}
        run: |
            docker buildx build --build-arg	VITE_OIDC_AUTHORITY=$VITE_OIDC_AUTHORITY --build-arg VITE_OIDC_CLIENT_ID=$VITE_OIDC_CLIENT_ID --platform linux/amd64,linux/arm64 --push -t ghcr.io/thiesjoo/heic-wallpaper/worker:latest -t ghcr.io/thiesjoo/heic-wallpaper/worker:${{ github.sha }} --target celery .
            docker buildx build --build-arg	VITE_OIDC_AUTHORITY=$VITE_OIDC_AUTHORITY --build-arg VITE_OIDC_CLIENT_ID=$VITE_OIDC_CLIENT_ID --platform linux/amd64,linux/arm64 --push -t ghcr.io/thiesjoo/heic-wallpaper/frontend:latest -t ghcr.io/thiesjoo/heic-wallpaper/frontend:${{ github.sha }} --target nginx-prod .
            docker buildx build --build-arg	VITE_OIDC_AUTHORITY=$VITE_OIDC_AUTHORITY --build-arg VITE_OIDC_CLIENT_ID=$VITE_OIDC_CLIENT_ID --platform linux/amd64,linux/arm64 --push -t ghcr.io/thiesjoo/heic-wallpaper/backend:latest -t ghcr.io/thiesjoo/heic-wallpaper/backend:${{ github.sha }} --target backend-prod .
