name: CI/CD
on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v2.3.4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          build-args: |
            "VITE_OIDC_AUTHORITY=${{ vars.VITE_OIDC_AUTHORITY }}"
            "VITE_OIDC_CLIENT_ID=${{ vars.VITE_OIDC_CLIENT_ID }}"
          platforms: |
            "linux/amd64"
            "linux/arm64"
          tags: |
            "ghcr.io/thiesjoo/heic-wallpaper/worker:${{ steps.extract_branch.outputs.branch }}"
            "ghcr.io/thiesjoo/heic-wallpaper/worker:${{ github.sha }}"
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: celery
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          build-args: |
            "VITE_OIDC_AUTHORITY=${{ vars.VITE_OIDC_AUTHORITY }}"
            "VITE_OIDC_CLIENT_ID=${{ vars.VITE_OIDC_CLIENT_ID }}"
          platforms: |
            "linux/amd64"
            "linux/arm64"
          tags: |
            "ghcr.io/thiesjoo/heic-wallpaper/backend:${{ steps.extract_branch.outputs.branch }}"
            "ghcr.io/thiesjoo/heic-wallpaper/backend:${{ github.sha }}"
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: backend-prod
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          build-args: |
            "VITE_OIDC_AUTHORITY=${{ vars.VITE_OIDC_AUTHORITY }}"
            "VITE_OIDC_CLIENT_ID=${{ vars.VITE_OIDC_CLIENT_ID }}"
          platforms: |
            "linux/amd64"
            "linux/arm64"
          tags: |
            "ghcr.io/thiesjoo/heic-wallpaper/frontend:${{ steps.extract_branch.outputs.branch }}"
            "ghcr.io/thiesjoo/heic-wallpaper/frontend:${{ github.sha }}"
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: nginx-prod
