name: CI/CD
on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        # Push tag celery as worker
        # Push tag nginx-prod as frontend
        # Push tag backend-prod as backend
        run: |
            docker buildx build --platform linux/amd64,linux/arm64 --push -t ghcr.io/thiesjoo/heic-wallpaper/worker:latest -t ghcr.io/thiesjoo/heic-wallpaper/celery:${{ github.sha }} --target celery .
            docker buildx build --platform linux/amd64,linux/arm64 --push -t ghcr.io/thiesjoo/heic-wallpaper/frontend:latest -t ghcr.io/thiesjoo/heic-wallpaper/nginx-prod:${{ github.sha }} --target nginx-prod .
            docker buildx build --platform linux/amd64,linux/arm64 --push -t ghcr.io/thiesjoo/heic-wallpaper/backend:latest -t ghcr.io/thiesjoo/heic-wallpaper/backend-prod:${{ github.sha }} --target backend-prod .